/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ToolAliasEntry =
  | string
  | {
      /**
       * where the alias goes
       */
      backend?: string;
      versions?: ToolAliasVersions;
      /**
       * version alias points to
       */
      [k: string]: string;
    };
export type EnvDirective = {
  path?: EnvPath;
  paths?: EnvPaths;
  tools?: EnvTools;
  expand?: EnvFileExpand;
  redact?: EnvRedact;
  required?: EnvRequired;
  [k: string]: unknown;
} & EnvDirective1;
export type EnvPath = string | string[];
export type EnvPaths = string[];
/**
 * load tools before resolving
 */
export type EnvTools = boolean;
/**
 * enable shell-style variable expansion for values loaded by env._.file
 */
export type EnvFileExpand = boolean;
/**
 * redact the value from logs
 */
export type EnvRedact = boolean;
/**
 * require this environment variable to be defined before mise runs or in a later config file. Cannot be used with empty string values or value=false. Can be a boolean or a help string.
 */
export type EnvRequired = boolean | string;
export type EnvDirective1 =
  | {
      path: EnvPath;
      [k: string]: unknown;
    }
  | {
      paths: EnvPaths;
      [k: string]: unknown;
    };
/**
 * environment variable value; false removes the variable
 */
export type EnvValue = string | number | boolean;
/**
 * fallback value to use when the environment variable is unset or empty
 */
export type EnvDefault = string | number;
/**
 * [experimental] age-encrypted value (simplified format)
 */
export type EnvAge = string;
/**
 * [experimental] age-encrypted value
 */
export type EnvAgeValue = string;
/**
 * [experimental] compression format for the encrypted value
 */
export type EnvAgeFormat = "raw" | "zstd";
/**
 * task template that can be extended by tasks
 */
export type TaskTemplate = TaskProps & {
  hide?: never;
  interactive?: never;
  quiet?: never;
  raw?: never;
  raw_args?: never;
  [k: string]: unknown;
};
/**
 * task name and args
 */
export type TaskDependencyItem =
  | string
  | string[]
  | {
      task: string;
      args?: string[];
      env?: {
        [k: string]: string;
      };
      /**
       * do not fail when the task name or pattern has no matches
       */
      optional?: boolean;
      [k: string]: unknown;
    };
export type Tool =
  | string
  | (ToolOptions & {
      /**
       * environment variables during tool installation
       */
      install_env?: {
        [k: string]: EnvValue;
      };
      depends?: string | string[];
      /**
       * command to run after tool installation
       */
      postinstall?: string;
      [k: string]: unknown;
    });
export type ToolOptions = {
  /**
   * version of the tool to install
   */
  version?: string;
  /**
   * path to a custom compiled version
   */
  path?: string;
  /**
   * version prefix to resolve
   */
  prefix?: string;
  /**
   * version control reference to compile
   */
  ref?: string;
  os?: OsFilter;
  [k: string]: unknown;
} & ToolOptions1;
/**
 * operating system filters to install on
 */
export type OsFilter = OsFilterItem | OsFilterItem[];
/**
 * operating system or os/arch pair to install on
 */
export type OsFilterItem = string;
export type ToolOptions1 = {
  [k: string]: unknown;
};
export type TaskRunEntry =
  | string
  | {
      /**
       * single task name to run
       */
      task: string;
      /**
       * arguments to pass to the task
       */
      args?: string[];
      /**
       * environment variables to set for the task
       */
      env?: {
        [k: string]: string;
      };
      [k: string]: unknown;
    }
  | {
      /**
       * parallel task group to run
       */
      tasks: string[];
      [k: string]: unknown;
    };
export type SystemdTimer = {
  [k: string]: unknown;
};
/**
 * command or commands to run for a bootstrap phase
 */
export type BootstrapHook =
  | string
  | string[]
  | {
      run: string | string[];
      [k: string]: unknown;
    };
export type BootstrapShellActivation =
  | boolean
  | ("activate" | "shims")
  | {
      /**
       * whether to manage the activation block
       */
      enabled: boolean;
      /**
       * activation mode; defaults according to the target
       */
      mode?: "activate" | "shims";
    };
export type Task =
  | string
  | string[]
  | (TaskProps & {
      /**
       * name of the task template to extend
       */
      extends?: string;
      [k: string]: unknown;
    });
export type HookDefinition = HookDefinitionItem | HookDefinitionItem[];
export type HookDefinitionItem =
  | HookRunString
  | HookRunTable
  | HookCurrentShellScriptTable
  | HookCurrentShellScriptsTable
  | HookSpawnedScriptTable
  | HookSpawnedScriptsTable
  | HookTaskRef;
/**
 * inline hook command to run
 */
export type HookRunString = string;
export type HookRunTable = HookRunTable1 & {
  /**
   * inline hook command to run
   */
  run?: string;
  /**
   * inline hook command to run on Windows
   */
  run_windows?: string;
  /**
   * inline shell command to use for run hooks, such as "bash -c"
   */
  shell?: string;
  [k: string]: unknown;
};
export type HookRunTable1 = {
  [k: string]: unknown;
};
/**
 * scripts to evaluate in the active shell for enter/leave/cd hooks
 */
export type HookScriptsValue = string[];
/**
 * deprecated alias for run when an enter/leave/cd hook has no shell
 */
export type HookScriptsValue1 = string[];
export type HookInstallDefinition = HookInstallDefinitionItem | HookInstallDefinitionItem[];
export type HookInstallDefinitionItem =
  HookRunString | HookRunTable | HookInstallScriptTable | HookInstallScriptsTable | HookTaskRef;
/**
 * deprecated alias for run in preinstall/postinstall hooks; joins the scripts and executes them in a subprocess
 */
export type HookScriptsValue2 = string[];
/**
 * files to watch for changes and run scripts when modified
 */
export type WatchFiles = (
  | {
      /**
       * script to run when file changes
       */
      run: string;
      /**
       * inline shell command used to run script when file changes
       */
      shell?: string;
      /**
       * patterns to watch for
       */
      patterns: string[];
      [k: string]: unknown;
    }
  | {
      /**
       * mise task to run when file changes
       */
      task: string;
      /**
       * patterns to watch for
       */
      patterns: string[];
      [k: string]: unknown;
    }
)[];

/**
 * config file for mise version manager (mise.toml)
 */
export interface Mise {
  /**
   * @deprecated
   * custom shorthands
   */
  alias?: {
    [k: string]: ToolAliasEntry;
  };
  /**
   * Tool version aliases
   */
  tool_alias?: {
    [k: string]: ToolAliasEntry;
  };
  /**
   * shell aliases
   */
  shell_alias?: {
    /**
     * command to run
     */
    [k: string]: string;
  };
  /**
   * environment variables to set
   */
  env?: Env | Env[];
  /**
   * @deprecated
   * dotenv file(s) to load. Deprecated; use env._.file instead. This will be removed in mise 2027.4.0.
   */
  env_file?: string | string[];
  /**
   * @deprecated
   * dotenv file(s) to load. Deprecated; use env._.file instead. This will be removed in mise 2027.4.0.
   */
  dotenv?: string | string[];
  /**
   * @deprecated
   * PATH entries to add. Deprecated; use env._.path instead. This will be removed in mise 2027.4.0.
   */
  env_path?: string | string[];
  /**
   * marks this config as a monorepo root for task path syntax
   */
  monorepo_root?: boolean;
  monorepo?: Monorepo;
  /**
   * minimum version of mise required to use this config
   */
  min_version?:
    | string
    | {
        /**
         * error if current mise is lower than this version
         */
        hard?: string;
        /**
         * warn if current mise is lower than this version
         */
        soft?: string;
        [k: string]: unknown;
      };
  /**
   * env or vars keys to redact from logs
   */
  redactions?: string[];
  /**
   * plugins to use
   */
  plugins?: {
    /**
     * url to plugin repository
     */
    [k: string]: string;
  };
  /**
   * configure deps providers
   */
  deps?: {
    /**
     * Disable specific deps providers
     */
    disable?: string[];
    npm?: DepsProvider;
    yarn?: DepsProvider;
    pnpm?: DepsProvider;
    bun?: DepsProvider;
    go?: DepsProvider;
    pip?: DepsProvider;
    poetry?: DepsProvider;
    uv?: DepsProvider;
    bundler?: DepsProvider;
    composer?: DepsProvider;
    dart?: DepsProvider;
    flutter?: DepsProvider;
    [k: string]: DepsProvider;
  };
  /**
   * configuration for `mise oci build`
   */
  oci?: {
    /**
     * Base image reference (overrides the oci.default_from setting)
     */
    from?: string;
    /**
     * Default tag applied to the built image
     */
    tag?: string;
    /**
     * Working directory baked into the image config
     */
    workdir?: string;
    /**
     * Entrypoint baked into the image config
     */
    entrypoint?: string[];
    /**
     * Cmd baked into the image config
     */
    cmd?: string[];
    /**
     * User baked into the image config
     */
    user?: string;
    /**
     * Numeric UID assigned to tar layer entries
     */
    user_id?: number;
    /**
     * Numeric GID assigned to tar layer entries. Defaults to user_id when unset
     */
    group_id?: number;
    /**
     * Override where mise installs go in the image (default /mise)
     */
    mount_point?: string;
    /**
     * Host files or directories copied into the image as independent layers
     */
    copy?: {
      /**
       * host path to copy, relative to the config file when not absolute
       */
      host: string;
      /**
       * absolute non-root image path without `.` or `..` components
       */
      image: string;
    }[];
    /**
     * Extra env vars baked into the image config
     */
    env?: {
      [k: string]: string;
    };
    /**
     * Labels baked into the image config
     */
    labels?: {
      [k: string]: string;
    };
    [k: string]: unknown;
  };
  settings?: Settings;
  /**
   * dotfiles applied with `mise dotfiles apply` or `mise bootstrap`, keyed by target path
   */
  dotfiles?: {
    [k: string]:
      | string
      | {
          /**
           * source file or directory
           */
          source?: string;
          /**
           * how to apply a whole-file source to the target; omitted uses dotfiles.default_mode
           */
          mode?: (("symlink" | "symlink-each" | "copy" | "template") | string) & string;
          /**
           * glob patterns to skip when the mode walks a source directory (symlink-each, or copy with a directory source); a pattern without "/" matches any path component, one with "/" is anchored to the source root
           */
          exclude?: string[];
          /**
           * block content, maintained between marker comments
           */
          block?: string;
          /**
           * template engine to render block content with; currently only "tera"
           */
          template?: ("tera" | string) & string;
          /**
           * exact line to ensure exists (appended if absent)
           */
          line?: string;
          /**
           * comment prefix for edit marker lines; inferred from the file extension when omitted
           */
          comment?: string;
          [k: string]: unknown;
        };
  };
  /**
   * machine-global bootstrapping (system packages, repos, macOS defaults, launchd agents, login shell)
   */
  bootstrap?: {
    /**
     * independent config roots whose dotfiles and managed files/directories are composed into bootstrap
     */
    config_roots?: string[];
    /**
     * package manager plugins to install with `mise bootstrap plugins apply`, keyed by manager name
     */
    plugins?: {
      /**
       * plugin git URL
       */
      [k: string]: string;
    };
    /**
     * system packages to install with `mise bootstrap packages apply`, keyed by "manager:package" (e.g. "apt:libssl-dev", "brew:postgresql@17", "dnf:openssl-devel", "pacman:base-devel")
     */
    packages?: {
      [k: string]:
        | string
        | {
            /**
             * version pin in the manager's native format, or "latest"
             */
            version?: string;
            /**
             * operating system or OS/architecture selectors
             */
            os?: OsFilterItem | [OsFilterItem, ...OsFilterItem[]];
            /**
             * adopt an existing identical brew-cask app artifact instead of replacing it
             */
            adopt?: boolean;
          };
    };
    /**
     * git repositories to clone or update with `mise bootstrap repos apply`, keyed by target path
     */
    repos?: {
      [k: string]: {
        /**
         * git repository URL
         */
        url: string;
        /**
         * optional branch, tag, or full commit SHA to check out
         */
        ref?: string;
      };
    };
    /**
     * macOS-specific bootstrap config
     */
    macos?: {
      /**
       * curated Dock preferences that compile into macOS defaults
       */
      dock?: {
        /**
         * hide and show the Dock automatically
         */
        autohide?: boolean;
        /**
         * Dock screen edge
         */
        orientation?: "bottom" | "left" | "right";
        /**
         * Dock icon size
         */
        tilesize?: number;
        /**
         * enable Dock magnification
         */
        magnification?: boolean;
        /**
         * Dock magnified icon size
         */
        largesize?: number;
        /**
         * show recent applications in the Dock
         */
        show_recents?: boolean;
        /**
         * automatically rearrange Spaces based on most recent use
         */
        mru_spaces?: boolean;
      };
      /**
       * curated Finder preferences that compile into macOS defaults
       */
      finder?: {
        /**
         * show hidden files in Finder
         */
        show_all_files?: boolean;
        /**
         * show the Finder path bar
         */
        show_pathbar?: boolean;
        /**
         * show the Finder status bar
         */
        show_status_bar?: boolean;
        /**
         * show the warning when changing file extensions
         */
        show_extensions_warning?: boolean;
        /**
         * Finder preferred view style
         */
        preferred_view_style?: "icon" | "list" | "column" | "gallery";
      };
      /**
       * curated keyboard preferences that compile into macOS defaults
       */
      keyboard?: {
        /**
         * keyboard repeat interval
         */
        key_repeat?: number;
        /**
         * delay before key repeat starts
         */
        initial_key_repeat?: number;
        /**
         * enable press-and-hold accent picker
         */
        press_and_hold?: boolean;
        /**
         * use F1, F2, etc. as standard function keys
         */
        fn_state?: boolean;
      };
      /**
       * curated trackpad preferences that compile into macOS defaults
       */
      trackpad?: {
        /**
         * enable tap to click for built-in and Bluetooth trackpads
         */
        tap_to_click?: boolean;
        /**
         * enable three finger drag for built-in and Bluetooth trackpads
         */
        three_finger_drag?: boolean;
      };
      /**
       * macOS user defaults to apply with `mise bootstrap macos defaults apply`, keyed by preferences domain (e.g. "com.apple.dock", "NSGlobalDomain")
       */
      defaults?: {
        /**
         * defaults keys and their desired values for this domain
         */
        [k: string]: {
          /**
           * desired value, written with the matching `defaults write` type (-bool, -int, -float, -string)
           */
          [k: string]: boolean | number | string;
        };
      };
      /**
       * macOS launchd bootstrap config
       */
      launchd?: {
        /**
         * macOS user LaunchAgents to write and load with `mise bootstrap macos launchd-agents apply`
         */
        agents?: {
          [k: string]: {
            /**
             * program path for ProgramArguments[0]
             */
            program: string;
            /**
             * additional ProgramArguments entries
             */
            args?: string[];
            /**
             * write RunAtLoad
             */
            run_at_load?: boolean;
            /**
             * write KeepAlive
             */
            keep_alive?: boolean;
            /**
             * write StartInterval in seconds
             */
            start_interval?: number;
            /**
             * write ThrottleInterval in seconds
             */
            throttle_interval?: number;
            /**
             * write QueueDirectories (absolute paths; `~` and `~/` are expanded)
             */
            queue_directories?: string[];
            /**
             * write one or more StartCalendarInterval schedules
             */
            start_calendar_interval?: LaunchdCalendarInterval | [LaunchdCalendarInterval, ...LaunchdCalendarInterval[]];
            /**
             * environment variables for EnvironmentVariables
             */
            environment?: {
              [k: string]: string;
            };
            /**
             * write WorkingDirectory
             */
            working_directory?: string;
            /**
             * write StandardOutPath
             */
            stdout_path?: string;
            /**
             * write StandardErrorPath
             */
            stderr_path?: string;
            /**
             * run `launchctl kickstart -k` after loading the agent
             */
            kickstart?: boolean;
            [k: string]: unknown;
          };
        };
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    /**
     * Linux-specific bootstrap config
     */
    linux?: {
      /**
       * Linux host firewall policy and rules managed with `mise bootstrap firewall`
       */
      firewall?: {
        /**
         * firewall backend; auto reuses managed or active host infrastructure
         */
        backend?: "auto" | "ufw" | "firewalld" | "nftables";
        /**
         * desired lifecycle of mise-managed firewall state
         */
        state?: "enabled" | "disabled" | "absent";
        /**
         * default action for incoming traffic
         */
        default_incoming?: "allow" | "deny" | "reject";
        /**
         * default action for outgoing traffic
         */
        default_outgoing?: "allow" | "deny" | "reject";
        /**
         * treat the declared rules as the complete owned ruleset; UFW reset also removes unrelated UFW rules
         */
        exclusive?: boolean;
        /**
         * allow default-deny or reject over SSH without a rule covering the connected peer
         */
        allow_lockout?: boolean;
        /**
         * named firewall rules reconciled without deleting undeclared managed rules
         */
        rules?: {
          /**
           * stable managed rule identifier
           */
          name: string;
          state?: "present" | "absent";
          direction?: "incoming" | "outgoing";
          action?: "allow" | "deny" | "reject";
          /**
           * single port number or inclusive range
           */
          port?: number | string;
          protocol?: "tcp" | "udp" | "sctp" | "dccp";
          /**
           * source IPv4 or IPv6 CIDR network
           */
          source?: string;
          /**
           * destination IPv4 or IPv6 CIDR network
           */
          destination?: string;
          /**
           * network interface (nftables and UFW only)
           */
          interface?: string;
        }[];
      };
      /**
       * systemd user service and timer bootstrap config
       */
      systemd?: {
        /**
         * systemd user services and timers to write and start with `mise bootstrap linux systemd-units apply`
         */
        units?: {
          [k: string]: SystemdService | SystemdTimer;
        };
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    /**
     * current-user bootstrap settings
     */
    user?: {
      /**
       * current user's desired login shell, applied with `chsh -s`; must be an absolute path
       */
      login_shell?: string;
      [k: string]: unknown;
    };
    /**
     * Homebrew-specific bootstrap package config
     */
    brew?: {
      /**
       * adopt existing app artifacts by default for configured brew-cask packages
       */
      adopt?: boolean;
      /**
       * Homebrew tap names mapped to custom git URLs
       */
      taps?: {
        [k: string]: string;
      };
      [k: string]: unknown;
    };
    /**
     * commands to run before and after bootstrap phases
     */
    hooks?: {
      "pre-packages"?: BootstrapHook;
      pre_packages?: BootstrapHook;
      "post-packages"?: BootstrapHook;
      post_packages?: BootstrapHook;
      "pre-repos"?: BootstrapHook;
      pre_repos?: BootstrapHook;
      "post-repos"?: BootstrapHook;
      post_repos?: BootstrapHook;
      "pre-dotfiles"?: BootstrapHook;
      pre_dotfiles?: BootstrapHook;
      "post-dotfiles"?: BootstrapHook;
      post_dotfiles?: BootstrapHook;
      "pre-defaults"?: BootstrapHook;
      pre_defaults?: BootstrapHook;
      "post-defaults"?: BootstrapHook;
      post_defaults?: BootstrapHook;
      "pre-user"?: BootstrapHook;
      pre_user?: BootstrapHook;
      "post-user"?: BootstrapHook;
      post_user?: BootstrapHook;
      "pre-tools"?: BootstrapHook;
      pre_tools?: BootstrapHook;
      "post-tools"?: BootstrapHook;
      post_tools?: BootstrapHook;
      final?: BootstrapHook;
    };
    /**
     * declarative mise shell activation snippets, applied with `mise bootstrap mise-shell-activate apply`
     */
    mise_shell_activate?: {
      bash?: BootstrapShellActivation;
      zsh?: BootstrapShellActivation;
      fish?: BootstrapShellActivation;
      bash_profile?: BootstrapShellActivation;
      bashrc?: BootstrapShellActivation;
      zshenv?: BootstrapShellActivation;
      zprofile?: BootstrapShellActivation;
      zshrc?: BootstrapShellActivation;
    };
    [k: string]: unknown;
  };
  task_config?: TaskConfig;
  tool_config?: ToolConfig;
  /**
   * task runner tasks
   */
  tasks?: {
    [k: string]: Task;
  };
  /**
   * task templates that can be extended by tasks via extends
   */
  task_templates?: {
    [k: string]: TaskTemplate;
  };
  /**
   * dev tools to use
   */
  tools?: {
    [k: string]: Tool[] | Tool;
  };
  hooks?: Hooks;
  vars?: Vars1;
  watch_files?: WatchFiles;
  _?: {
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * tool version aliases
 */
export interface ToolAliasVersions {
  /**
   * version alias points to
   */
  [k: string]: string;
}
/**
 * environment variables
 */
export interface Env {
  /**
   * environment modules
   */
  _?: {
    file?: EnvDirective | string | (string | EnvDirective)[];
    path?:
      | (
          | {
              path: EnvPath;
              [k: string]: unknown;
            }
          | {
              paths: EnvPaths;
              [k: string]: unknown;
            }
        )
      | string
      | (
          | string
          | {
              path?: EnvPath;
              tools?: EnvTools;
              [k: string]: unknown;
            }
        )[];
    /**
     * python environment
     */
    python?: {
      venv?:
        | string
        | {
            /**
             * create a new virtual environment if one does not exist
             */
            create?: boolean;
            /**
             * path to python virtual environment to use
             */
            path: string;
            /**
             * python version to use
             */
            python?: string;
            /**
             * additional arguments to pass to python when creating a virtual environment
             */
            python_create_args?: string[];
            /**
             * additional arguments to pass to uv when creating a virtual environment
             */
            uv_create_args?: string[];
            [k: string]: unknown;
          };
      [k: string]: unknown;
    };
    source?: EnvDirective | string | (string | EnvDirective)[];
    [k: string]: unknown;
  };
  [k: string]:
    | {
        value: EnvValue;
        tools?: EnvTools;
        redact?: EnvRedact;
        required?: EnvRequired;
        [k: string]: unknown;
      }
    | {
        default: EnvDefault;
        tools?: EnvTools;
        redact?: EnvRedact;
        [k: string]: unknown;
      }
    | {
        tools?: EnvTools;
        redact?: EnvRedact;
        required: EnvRequired;
        [k: string]: unknown;
      }
    | {
        age: EnvAge;
        tools?: EnvTools;
        redact?: EnvRedact;
        required?: EnvRequired;
        [k: string]: unknown;
      }
    | {
        /**
         * [experimental] age-encrypted value (complex format)
         */
        age: {
          value: EnvAgeValue;
          format?: EnvAgeFormat;
          tools?: EnvTools;
          redact?: EnvRedact;
          required?: EnvRequired;
          [k: string]: unknown;
        };
        [k: string]: unknown;
      }
    | EnvValue;
}
/**
 * configuration for monorepo task discovery
 */
export interface Monorepo {
  /**
   * Explicit list of config root paths for monorepo task discovery. Supports single-level glob patterns (*). When set, skips filesystem walking for better performance.
   */
  config_roots?: string[];
  /**
   * Use a single lockfile at the monorepo root for descendant config roots. true opts in now, false keeps lockfiles next to subproject configs, and unset keeps the current behavior until the scheduled default flip.
   */
  lockfile?: boolean;
  /**
   * Experimental task defaults applied by task name across inferred and explicit workspace projects
   */
  task_defaults?: {
    [k: string]: TaskTemplate;
  };
  /**
   * Experimental explicit additions, removals, and overrides applied to provider-inferred workspace projects
   */
  projects?: {
    [k: string]: {
      /**
       * Remove this project and every dependency edge connected to it
       */
      remove?: boolean;
      /**
       * Add the project at this workspace-relative root or replace its inferred root
       */
      root?: string;
      /**
       * Replace provider-inferred project metadata
       */
      metadata?: {
        [k: string]: string;
      };
      /**
       * Replace the complete provider-inferred dependency set
       */
      depends?: string[];
      /**
       * Add dependency edges after an optional depends replacement
       */
      depends_add?: string[];
      /**
       * Remove dependency edges after an optional depends replacement
       */
      depends_remove?: string[];
      [k: string]: unknown;
    };
  };
  [k: string]: unknown;
}
/**
 * common task properties
 */
export interface TaskProps {
  alias?: string | string[];
  confirm?:
    | string
    | {
        /**
         * confirmation message before running this task
         */
        message: string;
        /**
         * default value for confirmation (yes/no/true/false)
         */
        default: "yes" | "no" | "y" | "n" | "true" | "false";
        [k: string]: unknown;
      };
  depends?: string | TaskDependencyItem[];
  depends_post?: string | TaskDependencyItem[];
  wait_for?: string | TaskDependencyItem[];
  /**
   * description of task
   */
  description?: string;
  /**
   * directory to run script in, default is the project's base directory
   */
  dir?: string;
  env?: Env;
  vars?: Vars;
  /**
   * tools to install/activate before running this task
   */
  tools?: {
    [k: string]: Tool;
  };
  /**
   * do not display this task
   */
  hide?: boolean;
  outputs?:
    | string[]
    | string
    | {
        /**
         * automatically touch an internal tracked file instead of specifying outputs
         */
        auto: true;
        [k: string]: unknown;
      };
  /**
   * experimental local artifact cache for declared task outputs
   */
  cache?: {
    /**
     * store and restore task outputs from the local mise cache
     */
    enabled?: boolean;
    /**
     * report project files read or written outside declared cache sources and outputs
     */
    audit?: boolean;
    /**
     * ambient environment variable names whose values affect the cache key
     */
    env?: string[];
    /**
     * commands whose stdout and stderr affect the cache key
     */
    command_inputs?: string[];
    [k: string]: unknown;
  };
  /**
   * experimental Rust compiler action cache configuration enabled only while this task runs
   */
  rust_cache?:
    | boolean
    | {
        enabled?: boolean;
        [k: string]: unknown;
      };
  /**
   * output style for this task (prefix, interleave, keep-order, replacing, timed, quiet, silent). Independent of the quiet/silent verbosity fields.
   */
  output?: "prefix" | "interleave" | "keep-order" | "replacing" | "timed" | "quiet" | "silent";
  /**
   * do not display mise information for this task
   */
  quiet?: boolean;
  /**
   * suppress all output for this task
   */
  silent?: boolean | ("stdout" | "stderr");
  /**
   * mark task as interactive, acquiring exclusive terminal access while allowing other non-interactive tasks to run in parallel
   */
  interactive?: boolean;
  /**
   * directly connect task to stdin/stdout/stderr
   */
  raw?: boolean;
  /**
   * skip mise's argument parsing for this task — all arguments (including --help/-h) are forwarded verbatim to the underlying command. Use for tasks that proxy a tool with its own argument parser.
   */
  raw_args?: boolean;
  run?: TaskRunEntry | TaskRunEntry[];
  run_windows?: TaskRunEntry | TaskRunEntry[];
  /**
   * Execute an external script
   */
  file?: string;
  sources?: string[] | string;
  watch?: TaskWatch;
  /**
   * specify a shell command to run the script with
   */
  shell?: string;
  /**
   * Specify usage (https://usage.jdx.dev/) specs for the task
   */
  usage?: string;
  /**
   * timeout for this task
   */
  timeout?: string;
  /**
   * block reads, writes, network, and env vars
   */
  deny_all?: boolean;
  /**
   * block filesystem reads
   */
  deny_read?: boolean;
  /**
   * block all filesystem writes
   */
  deny_write?: boolean;
  /**
   * block all network access
   */
  deny_net?: boolean;
  /**
   * block env var inheritance
   */
  deny_env?: boolean;
  /**
   * allow reads from specific paths
   */
  allow_read?: string[];
  /**
   * allow writes to specific paths
   */
  allow_write?: string[];
  /**
   * allow network to specific hosts
   */
  allow_net?: string[];
  /**
   * allow specific env vars through
   */
  allow_env?: string[];
  /**
   * experimental ambient env vars preserved under environment denial without affecting the task cache key
   */
  pass_through_env?: string[];
  [k: string]: unknown;
}
/**
 * variables to set
 */
export interface Vars {
  /**
   * vars modules
   */
  _?: {
    file?: string | string[];
    source?: string | string[];
    [k: string]: unknown;
  };
  [k: string]:
    | string
    | number
    | true
    | {
        value: string | number | true;
        redact?: EnvRedact;
        [k: string]: unknown;
      }
    | {
        default: EnvDefault;
        redact?: EnvRedact;
        [k: string]: unknown;
      }
    | {
        redact?: EnvRedact;
        required: true | string;
        [k: string]: unknown;
      }
    | {
        age: EnvAge;
        redact?: EnvRedact;
        [k: string]: unknown;
      }
    | {
        /**
         * [experimental] age-encrypted value (complex format)
         */
        age: {
          value: EnvAgeValue;
          format?: EnvAgeFormat;
          redact?: EnvRedact;
          [k: string]: unknown;
        };
        [k: string]: unknown;
      };
}
/**
 * options used by `mise watch` for this task
 */
export interface TaskWatch {
  /**
   * do not load VCS ignore files such as `.gitignore` when watching this task
   */
  no_vcs_ignore?: boolean;
  [k: string]: unknown;
}
/**
 * Prepare provider configuration
 */
export interface DepsProvider {
  /**
   * Auto-run before `mise x` and `mise run`
   */
  auto?: boolean;
  /**
   * Files/patterns to check for changes
   */
  sources?: string[];
  /**
   * Files/directories that should be newer than sources
   */
  outputs?: string[];
  /**
   * Command to run when stale
   */
  run?: string;
  /**
   * Environment variables to set
   */
  env?: {
    [k: string]: string;
  };
  /**
   * Working directory for the command
   */
  dir?: string;
  /**
   * Description shown in output
   */
  description?: string;
  /**
   * Other deps providers that must complete before this one runs
   */
  depends?: string[];
  /**
   * Timeout for the run command (e.g., "30s", "5m", "1h")
   */
  timeout?: string;
  [k: string]: unknown;
}
/**
 * mise settings
 */
export interface Settings {
  /**
   * Pushes tools' bin-paths to the front of PATH instead of allowing modifications of PATH after activation to take precedence.
   */
  activate_aggressive?: boolean;
  age?: {
    /**
     * [experimental] List of age identity files to use for decryption.
     */
    identity_files?: string[];
    /**
     * [experimental] Path to the age private key file to use for encryption/decryption.
     */
    key_file?: string;
    /**
     * [experimental] List of SSH identity files to use for age decryption.
     */
    ssh_identity_files?: string[];
    /**
     * If true, fail when age decryption fails (including when age is not available, the key is missing, or the key is invalid). If false, skip decryption and continue in these cases.
     */
    strict?: boolean;
    [k: string]: unknown;
  };
  /**
   * do not use precompiled binaries for any tool
   */
  all_compile?: boolean;
  /**
   * keep downloaded files after installation for debugging
   */
  always_keep_download?: boolean;
  /**
   * should mise keep install files after installation even if the installation fails
   */
  always_keep_install?: boolean;
  aqua?: {
    /**
     * Use baked-in aqua registry.
     */
    baked_registry?: boolean;
    /**
     * Use cosign to verify aqua tool signatures.
     */
    cosign?: boolean;
    /**
     * Enable GitHub Artifact Attestations verification for aqua tools.
     */
    github_attestations?: boolean;
    /**
     * Use minisign to verify aqua tool signatures.
     */
    minisign?: boolean;
    /**
     * Aqua registry sources to load before the baked-in registry.
     */
    registries?: string[];
    /**
     * How long to cache downloaded aqua registry source files.
     */
    registry_cache_ttl?: string;
    /**
     * @deprecated
     * [deprecated] URL of an aqua registry repository to fetch.
     */
    registry_url?: string;
    /**
     * Use SLSA to verify aqua tool signatures.
     */
    slsa?: boolean;
    [k: string]: unknown;
  };
  /**
   * Architecture to use for precompiled binaries.
   */
  arch?: string;
  /**
   * @deprecated
   * set to true to ensure .tool-versions will be compatible with asdf
   */
  asdf_compat?: boolean;
  /**
   * Automatically enable platform config environments (unix, {os}, {os}-{arch}).
   */
  auto_env?: boolean;
  /**
   * Automatically install missing tools when running `mise x`, `mise run`, or as part of the 'not found' handler.
   */
  auto_install?: boolean;
  /**
   * List of tools to skip automatically installing when running `mise x`, `mise run`, or as part of the 'not found' handler.
   */
  auto_install_disable_tools?: string[];
  /**
   * Delete files in cache that have not been accessed in this duration
   */
  cache_prune_age?: string;
  cargo?: {
    /**
     * Use cargo-binstall instead of cargo install if available
     */
    binstall?: boolean;
    /**
     * Use mise's native cargo binary installer when cargo-binstall is unavailable.
     */
    binstall_native?: boolean;
    /**
     * Require cargo-binstall for Cargo tools without an explicit Git source. Fail if no prebuilt binary is available or if tool options require cargo install.
     */
    binstall_only?: boolean;
    /**
     * Allow cargo-binstall to use third-party cargo-quickinstall artifacts.
     */
    binstall_quickinstall?: boolean;
    /**
     * Name of the cargo registry to use.
     */
    registry_name?: string;
    [k: string]: unknown;
  };
  /**
   * Path to change to after launching mise
   */
  cd?: string;
  /**
   * Directories where mise stops searching for config files.
   */
  ceiling_paths?: string[];
  /**
   * Set to true if running in a CI environment
   */
  ci?: boolean & string;
  /**
   * Use color in mise terminal output
   */
  color?: boolean;
  /**
   * Theme for interactive prompts (auto/default, charm, base16, catppuccin, dracula)
   */
  color_theme?: "auto" | "default" | "charm" | "base16" | "catppuccin" | "dracula";
  conda?: {
    /**
     * Default channel for conda packages.
     */
    channel?: string;
    [k: string]: unknown;
  };
  /**
   * Sets log level to debug
   */
  debug?: boolean;
  /**
   * The default config filename read. `mise use` and other commands that create new config files will use this value. This must be an env var.
   */
  default_config_filename?: string;
  /**
   * The default .tool-versions filename read. This will not ignore .tool-versions—use override_tool_versions_filename for that. This must be an env var.
   */
  default_tool_versions_filename?: string;
  /**
   * Backends to disable for new installs, such as `asdf`, `pipx`, or a vfox-backend plugin name. This does not uninstall or disable tools already installed with those backends.
   */
  disable_backends?: string[];
  /**
   * Disable the default mapping of short tool names like `php` -> `asdf:mise-plugins/asdf-php`. This parameter disables only for the backends `vfox` and `asdf`.
   */
  disable_default_registry?: boolean;
  /**
   * Turns off helpful hints when using different mise features
   */
  disable_hints?: string[];
  /**
   * Tools defined in mise.toml that should be ignored
   */
  disable_tools?: string[];
  dotfiles?: {
    /**
     * Default mode for dotfile entries when mode is omitted. Options: `symlink`, `symlink-each`, `copy`, `template`.
     */
    default_mode?: string;
    /**
     * Root directory used for implied dotfile sources.
     */
    root?: string;
    [k: string]: unknown;
  };
  dotnet?: {
    /**
     * Set DOTNET_CLI_TELEMETRY_OPTOUT to opt out of .NET CLI telemetry.
     */
    cli_telemetry_optout?: boolean;
    /**
     * Path to the shared .NET SDK root directory.
     */
    dotnet_root?: string;
    /**
     * Install each .NET SDK version in its own isolated directory.
     */
    isolated?: boolean;
    /**
     * @deprecated
     * [deprecated] Extends dotnet search and install abilities.
     */
    package_flags?: string[];
    /**
     * URL to fetch dotnet tools from.
     */
    registry_url?: string;
    [k: string]: unknown;
  };
  /**
   * Tools defined in mise.toml that should be used; unset enables all tools and empty disables all tools
   */
  enable_tools?: string[];
  /**
   * Env to use for mise.<MISE_ENV>.toml files.
   */
  env?: string[];
  /**
   * [experimental] Enable environment caching for nested mise invocations
   */
  env_cache?: boolean;
  /**
   * TTL for cached environments
   */
  env_cache_ttl?: string;
  /**
   * Path to a file containing environment variables to automatically load.
   */
  env_file?: string;
  /**
   * Controls shell-style variable expansion in env values (e.g., $FOO, ${BAR:-default})
   */
  env_shell_expand?: boolean;
  erlang?: {
    /**
     * If true, compile erlang from source. If false, use precompiled binaries. If not set, use precompiled binaries if available.
     */
    compile?: boolean;
    [k: string]: unknown;
  };
  /**
   * Automatically install missing tools when running `mise x`.
   */
  exec_auto_install?: boolean;
  /**
   * Enable experimental mise features which are incomplete or unstable—breakings changes may occur
   */
  experimental?: boolean;
  /**
   * How long to cache remote versions for tools.
   */
  fetch_remote_versions_cache?: string;
  /**
   * Timeout in seconds for HTTP requests to fetch new tool versions in mise.
   */
  fetch_remote_versions_timeout?: string;
  forgejo?: {
    /**
     * Shell command to run to obtain a Forgejo token for mise.
     */
    credential_command?: string;
    /**
     * Read Forgejo tokens from the fj CLI config.
     */
    fj_cli_tokens?: boolean;
    /**
     * Use git credential helpers to obtain Forgejo tokens.
     */
    use_git_credentials?: boolean;
    [k: string]: unknown;
  };
  github?: {
    /**
     * Shell command to run to obtain a GitHub token for mise.
     */
    credential_command?: string;
    /**
     * Read GitHub tokens from the gh CLI's hosts.yml config.
     */
    gh_cli_tokens?: boolean;
    /**
     * Enable GitHub Artifact Attestations verification for github backend tools.
     */
    github_attestations?: boolean;
    /**
     * GitHub API base URL for native OAuth token validation.
     */
    oauth_api_url?: string;
    /**
     * GitHub OAuth endpoint base URL for native device-flow tokens.
     */
    oauth_auth_url?: string;
    /**
     * GitHub App client ID for native OAuth device-flow tokens.
     */
    oauth_client_id?: string;
    /**
     * Environment variable name to export the native GitHub OAuth token under (empty disables).
     */
    oauth_export_env?: string;
    /**
     * Open the browser during native GitHub OAuth device flow.
     */
    oauth_open_browser?: boolean;
    /**
     * OAuth scopes requested for native GitHub device-flow tokens.
     */
    oauth_scopes?: string;
    /**
     * Enable SLSA provenance verification for github backend tools.
     */
    slsa?: boolean;
    /**
     * Use git credential helpers to obtain GitHub tokens.
     */
    use_git_credentials?: boolean;
    [k: string]: unknown;
  };
  /**
   * Enable GitHub Artifact Attestations verification for supported tools.
   */
  github_attestations?: boolean;
  gitlab?: {
    /**
     * Shell command to run to obtain a GitLab token for mise.
     */
    credential_command?: string;
    /**
     * Read GitLab tokens from the glab CLI config.
     */
    glab_cli_tokens?: boolean;
    /**
     * Use git credential helpers to obtain GitLab tokens.
     */
    use_git_credentials?: boolean;
    [k: string]: unknown;
  };
  /**
   * Use gix for git operations, set to false to shell out to git.
   */
  gix?: boolean;
  /**
   * Path to the global mise config file. Default is `~/.config/mise/config.toml`. This must be an env var.
   */
  global_config_file?: string;
  /**
   * Path which is used as `{{config_root}}` for the global config file. Default is `$HOME`. This must be an env var.
   */
  global_config_root?: string;
  go?: {
    /**
     * @deprecated
     * Path to a file containing default go packages to install when installing go.
     */
    default_packages_file?: string;
    /**
     * Mirror to download go sdk tarballs from.
     */
    download_mirror?: string;
    /**
     * URL to fetch go from.
     */
    repo?: string;
    /**
     * Changes where `go install` installs binaries to.
     */
    set_gobin?: boolean;
    /**
     * @deprecated
     * [deprecated] Set to true to set GOPATH=~/.local/share/mise/installs/go/.../packages.
     */
    set_gopath?: boolean;
    /**
     * Sets GOROOT=~/.local/share/mise/installs/go/.../.
     */
    set_goroot?: boolean;
    /**
     * Set to true to skip checksum verification when downloading go sdk tarballs.
     */
    skip_checksum?: boolean;
    [k: string]: unknown;
  };
  /**
   * @deprecated
   * Path to a file containing default go packages to install when installing go.
   */
  go_default_packages_file?: string;
  /**
   * @deprecated
   * Mirror to download go sdk tarballs from.
   */
  go_download_mirror?: string;
  /**
   * @deprecated
   * URL to fetch go from.
   */
  go_repo?: string;
  /**
   * @deprecated
   * Changes where `go install` installs binaries to.
   */
  go_set_gobin?: boolean;
  /**
   * @deprecated
   * [deprecated] Set to true to set GOPATH=~/.local/share/mise/installs/go/.../packages.
   */
  go_set_gopath?: boolean;
  /**
   * @deprecated
   * Sets GOROOT=~/.local/share/mise/installs/go/.../.
   */
  go_set_goroot?: boolean;
  /**
   * @deprecated
   * Set to true to skip checksum verification when downloading go sdk tarballs.
   */
  go_skip_checksum?: boolean;
  /**
   * Verify OpenPGP signatures for all tools (built-in, no external gpg required). Set to false to disable.
   */
  gpg_verify?: boolean;
  hook_env?: {
    /**
     * Cache hook-env directory checks for this duration. Useful for slow filesystems like NFS.
     */
    cache_ttl?: string;
    /**
     * Only run hook-env checks on directory change, not on every prompt.
     */
    chpwd_only?: boolean;
    [k: string]: unknown;
  };
  /**
   * Total time allowed for an HTTP download, including retries.
   */
  http_download_timeout?: string;
  /**
   * Number of retries for transient HTTP failures in mise.
   */
  http_retries?: number;
  /**
   * Timeout for connecting or waiting between reads during HTTP requests.
   */
  http_timeout?: string;
  /**
   * @deprecated
   * Set to false to disable the idiomatic version files such as .node-version, .ruby-version, etc.
   */
  idiomatic_version_file?: boolean;
  /**
   * Specific idiomatic version files to disable for a tool.
   */
  idiomatic_version_file_disable_files?: string[];
  /**
   * @deprecated
   * Specific tools to disable idiomatic version files for.
   */
  idiomatic_version_file_disable_tools?: string[];
  /**
   * Specific tools to enable idiomatic version files for like .node-version, .ruby-version, etc.
   */
  idiomatic_version_file_enable_tools?: string[];
  /**
   * This is a list of config paths that mise will ignore.
   */
  ignored_config_paths?: string[];
  /**
   * @deprecated
   * Minimum release age / supply chain protection — only install versions released before this date
   */
  install_before?: string;
  java?: {
    /**
     * Shorthand for Java. Used when installing Java without a vendor prefix.
     */
    shorthand_vendor?: string;
    [k: string]: unknown;
  };
  /**
   * How many jobs to run concurrently such as tool installs. Values below 1 are treated as 1.
   */
  jobs?: number;
  /**
   * @deprecated
   * Set to false to disable the idiomatic version files such as .node-version, .ruby-version, etc.
   */
  legacy_version_file?: boolean;
  /**
   * @deprecated
   * Specific tools to disable idiomatic version files for.
   */
  legacy_version_file_disable_tools?: string[];
  /**
   * Libc implementation to use for precompiled Linux binaries.
   */
  libc?: "glibc" | "gnu" | "musl";
  /**
   * Use libgit2 for git operations, set to false to shell out to git.
   */
  libgit2?: boolean;
  /**
   * Require lockfile URLs to be present during installation.
   */
  locked?: boolean;
  /**
   * Re-verify provenance at install time even when the lockfile already has provenance.
   */
  locked_verify_provenance?: boolean;
  /**
   * Create and read lockfiles for tool versions.
   */
  lockfile?: boolean;
  /**
   * Platforms to target in lockfile operations.
   */
  lockfile_platforms?: string[];
  /**
   * Show more/less output.
   */
  log_level?: "trace" | "debug" | "info" | "warn" | "error";
  /**
   * Minimum release age / supply chain protection — only install versions older than this threshold
   */
  minimum_release_age?: string;
  /**
   * Tools and backends to exclude from the global/default minimum_release_age setting
   */
  minimum_release_age_excludes?: string[];
  /**
   * Use a netrc file for HTTP Basic authentication.
   */
  netrc?: boolean;
  /**
   * Path to the netrc file to use for HTTP Basic authentication.
   */
  netrc_file?: string;
  /**
   * Do not load environment variables from config files.
   */
  no_env?: boolean;
  /**
   * Do not execute hooks from config files.
   */
  no_hooks?: boolean;
  node?: {
    /**
     * A list of patch files or URLs to apply to node source.
     */
    apply_patches?: string;
    /**
     * Additional CFLAGS options (e.g., to override -O3).
     */
    cflags?: string;
    /**
     * Compile node from source.
     */
    compile?: boolean;
    /**
     * How many jobs should be used in compilation.
     */
    concurrency?: number;
    /**
     * Additional ./configure options.
     */
    configure_opts?: string;
    /**
     * Installs the default corepack shims after installing any node version.
     */
    corepack?: boolean;
    /**
     * @deprecated
     * Path to a file containing default npm packages to install.
     */
    default_packages_file?: string;
    /**
     * Install a specific node flavor like glibc-217 or musl. Use with unofficial node build repo.
     */
    flavor?: string;
    /**
     * Verify OpenPGP signatures for node (built-in, no external gpg required). Set to false to disable.
     */
    gpg_verify?: boolean;
    /**
     * Make command to use.
     */
    make?: string;
    /**
     * Additional make install options.
     */
    make_install_opts?: string;
    /**
     * Additional make options.
     */
    make_opts?: string;
    /**
     * Mirror to download node tarballs from.
     */
    mirror_url?: string;
    /**
     * Use ninja instead of make to compile node.
     */
    ninja?: boolean;
    /**
     * Directory for nodenv.
     */
    nodenv_root?: string;
    /**
     * Install a bash wrapper at bin/npm that triggers `mise reshim` after `npm install -g`. Disable to let corepack or a global `npm install -g npm@...` manage `bin/npm` directly.
     */
    npm_shim?: boolean;
    /**
     * Directory for nvm.
     */
    nvm_dir?: string;
    /**
     * Verify the downloaded assets using GPG.
     */
    verify?: boolean;
    [k: string]: unknown;
  };
  /**
   * Set to false to disable the "command not found" handler to autoinstall missing tool versions.
   */
  not_found_auto_install?: boolean;
  /**
   * Set to false to stop shims from falling back to a same-named binary found elsewhere on PATH.
   */
  not_found_system_fallback?: boolean;
  npm?: {
    /**
     * @deprecated
     * Use bun instead of npm if bun is installed and on PATH.
     */
    bun?: boolean;
    /**
     * Package manager to use for installing npm packages.
     */
    package_manager?: "auto" | "npm" | "aube" | "aube_cli" | "bun" | "pnpm";
    /**
     * Shell out to the npm CLI for `npm:` version metadata and installs instead of mise's built-in aube-based implementation.
     */
    shell_out?: boolean;
    [k: string]: unknown;
  };
  oci?: {
    /**
     * Default base image for `mise oci build` when [oci].from is not set.
     */
    default_from?: string;
    /**
     * Path inside OCI images where mise tools are installed.
     */
    default_mount_point?: string;
    /**
     * Registries (host or host:port) contacted over plain HTTP instead of HTTPS.
     */
    insecure_registries?: string[];
    [k: string]: unknown;
  };
  /**
   * Disable all HTTP requests. Tools will only use locally cached data.
   */
  offline?: boolean;
  /**
   * OS to use for precompiled binaries.
   */
  os?: string;
  /**
   * If set, mise will ignore default config files like `mise.toml` and use these filenames instead.
   */
  override_config_filenames?: string[];
  /**
   * If set, mise will ignore .tool-versions files and use these filenames instead. Can be set to `none` to disable .tool-versions.
   */
  override_tool_versions_filenames?: string[];
  /**
   * Enables extra-secure behavior.
   */
  paranoid?: boolean;
  /**
   * Default to pinning versions when running `mise use` in mise.toml files.
   */
  pin?: boolean;
  pipx?: {
    /**
     * URL to use for pipx registry.
     */
    registry_url?: string;
    /**
     * Use uvx instead of pipx if uv is installed and on PATH.
     */
    uvx?: boolean;
    [k: string]: unknown;
  };
  /**
   * How long to wait before updating plugins automatically (note this isn't currently implemented).
   */
  plugin_autoupdate_last_check_duration?: string;
  /**
   * Prefer locally cached data over remote fetches when possible.
   */
  prefer_offline?: boolean;
  /**
   * Include pre-release versions in `ls-remote`, `latest` resolution, and fuzzy matching for all tools.
   */
  prereleases?: boolean;
  /**
   * @deprecated
   * Profile to use for mise.${MISE_PROFILE}.toml files.
   */
  profile?: string;
  /**
   * Fail when provenance API checks cannot be completed.
   */
  provenance_api_failures_fatal?: boolean;
  python?: {
    /**
     * If true, compile python from source. If false, use precompiled binaries. If not set, use precompiled binaries if available.
     */
    compile?: boolean;
    /**
     * @deprecated
     * Path to a file containing default python packages to install when installing a python version.
     */
    default_packages_file?: string;
    /**
     * Enable GitHub Artifact Attestations verification for precompiled Python binaries.
     */
    github_attestations?: boolean;
    /**
     * URL to fetch python patches from to pass to python-build.
     */
    patch_url?: string;
    /**
     * Directory to fetch python patches from.
     */
    patches_directory?: string;
    /**
     * Specify the architecture to use for precompiled binaries.
     */
    precompiled_arch?: string;
    /**
     * Specify the flavor to use for precompiled binaries.
     */
    precompiled_flavor?: string;
    /**
     * Specify the OS to use for precompiled binaries.
     */
    precompiled_os?: string;
    /**
     * URL to fetch pyenv from for compiling python with python-build.
     */
    pyenv_repo?: string;
    /**
     * Integrate with uv to manage project venvs when uv.lock is present.
     */
    uv_venv_auto?: (boolean | string) & (false | "source" | "create|source" | true);
    /**
     * Arguments to pass to uv when creating a venv.
     */
    uv_venv_create_args?: string[];
    /**
     * Arguments to pass to python when creating a venv. (not used for uv venv creation)
     */
    venv_create_args?: string[];
    /**
     * Prefer to use venv from Python's standard library.
     */
    venv_stdlib?: boolean;
    [k: string]: unknown;
  };
  /**
   * Suppress all output except errors.
   */
  quiet?: boolean;
  /**
   * Connect stdin/stdout/stderr to child processes.
   */
  raw?: boolean;
  /**
   * How long to cache the floating mise registry.
   */
  registry_cache_ttl?: string;
  /**
   * Fetch the latest released mise registry and current aqua registry instead of using only the snapshots baked into this mise release.
   */
  registry_floating?: boolean;
  ruby?: {
    /**
     * A list of patch files or URLs to apply to ruby source.
     */
    apply_patches?: string;
    /**
     * If true, compile ruby from source. If false, require precompiled binaries. If not set, use precompiled binaries if available.
     */
    compile?: boolean;
    /**
     * @deprecated
     * Path to a file containing default ruby gems to install when installing ruby.
     */
    default_packages_file?: string;
    /**
     * Enable GitHub Artifact Attestations verification for precompiled Ruby binaries.
     */
    github_attestations?: boolean;
    /**
     * Override architecture identifier for precompiled Ruby binaries.
     */
    precompiled_arch?: string;
    /**
     * Override OS identifier for precompiled Ruby binaries.
     */
    precompiled_os?: string;
    /**
     * URL template or GitHub repo for precompiled Ruby binaries.
     */
    precompiled_url?: string;
    /**
     * CLI options passed directly to ruby-build before the version and install prefix.
     */
    ruby_build_cli_opts?: string;
    /**
     * Configure arguments passed through ruby-build after `--`.
     */
    ruby_build_opts?: string;
    /**
     * The URL used to fetch ruby-build. This accepts either a Git repository or a ZIP archive.
     */
    ruby_build_repo?: string;
    /**
     * Use ruby-install instead of ruby-build.
     */
    ruby_install?: boolean;
    /**
     * Options to pass to ruby-install.
     */
    ruby_install_opts?: string;
    /**
     * The URL used to fetch ruby-install. This accepts either a Git repository or a ZIP archive.
     */
    ruby_install_repo?: string;
    /**
     * Set to true to enable verbose output during ruby installation.
     */
    verbose_install?: boolean;
    [k: string]: unknown;
  };
  rust?: {
    /**
     * Path to the cargo home directory. Defaults to `~/.cargo` or `%USERPROFILE%\.cargo`
     */
    cargo_home?: string;
    /**
     * Default host triple to pass to `rustup init` via `--default-host`.
     */
    default_host?: string;
    /**
     * Path to the rustup home directory. Defaults to `~/.rustup` or `%USERPROFILE%\.rustup`
     */
    rustup_home?: string;
    [k: string]: unknown;
  };
  /**
   * Prevent project configuration from executing code during config loading and version resolution.
   */
  safe?: boolean;
  sandbox?: {
    /**
     * Deny filesystem reads and writes, network access, and environment variable inheritance by default for `mise run` and `mise exec`.
     */
    deny_all?: boolean;
    /**
     * Deny environment variable inheritance by default for `mise run` and `mise exec`.
     */
    deny_env?: boolean;
    /**
     * Deny network access by default for `mise run` and `mise exec`.
     */
    deny_net?: boolean;
    /**
     * Deny filesystem reads by default for `mise run` and `mise exec`.
     */
    deny_read?: boolean;
    /**
     * Deny filesystem writes by default for `mise run` and `mise exec`.
     */
    deny_write?: boolean;
    [k: string]: unknown;
  };
  /**
   * Additional read-only directories to search for installed tool versions.
   */
  shared_install_dirs?: string[];
  /**
   * @deprecated
   * [deprecated] Path to a file containing custom tool shorthands.
   */
  shorthands_file?: string;
  /**
   * Suppress all `mise run|watch` output except errors—including what tasks output.
   */
  silent?: boolean;
  /**
   * Enable SLSA provenance verification globally.
   */
  slsa?: boolean;
  sops?: {
    /**
     * The age private key to use for sops secret decryption. Takes precedence over standard SOPS_AGE_KEY environment variable.
     */
    age_key?: string;
    /**
     * Path to the age private key file for sops secret decryption. Takes precedence over standard SOPS_AGE_KEY_FILE environment variable.
     */
    age_key_file?: string;
    /**
     * The age public keys to use for sops secret encryption.
     */
    age_recipients?: string;
    /**
     * Use rops to decrypt sops files. Disable to shell out to `sops` which will slow down mise but sops may offer features not available in rops. Required for TOML SOPS files because the sops CLI does not support TOML.
     */
    rops?: boolean;
    /**
     * If true, fail when sops decryption fails (including when sops is not available, the key is missing, or the key is invalid). If false, skip decryption and continue in these cases.
     */
    strict?: boolean;
    [k: string]: unknown;
  };
  spm?: {
    /**
     * Only use SwiftPM artifact bundles for installation, fail if no matching bundle is available.
     */
    artifactbundle_only?: boolean;
    [k: string]: unknown;
  };
  status?: {
    /**
     * Show a warning if tools are not installed when entering a directory with a mise.toml file.
     */
    missing_tools?: string;
    /**
     * Show warning when deps providers have stale dependencies.
     */
    show_deps_stale?: boolean;
    /**
     * Show configured env vars when entering a directory with a mise.toml file.
     */
    show_env?: boolean;
    /**
     * Show configured tools when entering a directory with a mise.toml file.
     */
    show_tools?: boolean;
    /**
     * Truncate status messages.
     */
    truncate?: boolean;
    [k: string]: unknown;
  };
  swift?: {
    /**
     * Verify OpenPGP signatures for swift (built-in, no external gpg required). Set to false to disable.
     */
    gpg_verify?: boolean;
    /**
     * Override the platform to use for precompiled binaries.
     */
    platform?: string;
    [k: string]: unknown;
  };
  /**
   * Path to the system mise config file. Default is `/etc/mise/config.toml`. This must be an env var.
   */
  system_config_file?: string;
  /**
   * How to handle a plugin's declared system dependencies before installing a tool.
   */
  system_deps?: "prompt" | "auto" | "warn" | "ignore";
  system_packages?: {
    /**
     * Restrict which system package managers mise will use.
     */
    managers?: string[];
    /**
     * Allow `mise bootstrap packages apply` to elevate with sudo when not running as root.
     */
    sudo?: boolean;
    [k: string]: unknown;
  };
  task?: {
    /**
     * [experimental] Workspace providers from which to automatically infer tasks.
     */
    auto_infer?: string[];
    cache?: {
      /**
       * [experimental] File to write the complete task cache audit report to.
       */
      audit_report?: string;
      /**
       * [experimental] Remote task and action cache access mode.
       */
      remote_mode?: "read-write" | "read-only" | "write-only";
      /**
       * [experimental] Namespace sent to the remote build cache.
       */
      remote_namespace?: string;
      /**
       * [experimental] Audience for an automatically acquired remote cache OIDC token.
       */
      remote_oidc_audience?: string;
      /**
       * [experimental] Bearer token for remote build-cache authentication.
       */
      remote_token?: string;
      /**
       * [experimental] File containing a remote build-cache bearer token.
       */
      remote_token_file?: string;
      /**
       * [experimental] Base URL for the remote build-cache service.
       */
      remote_url?: string;
      /**
       * [experimental] File to write action-cache session statistics to.
       */
      stats_report?: string;
      [k: string]: unknown;
    };
    /**
     * [experimental] Directory for task output cache artifacts.
     */
    cache_dir?: string;
    /**
     * [experimental] Maximum age of task output cache entries since their last access.
     */
    cache_max_age?: string;
    /**
     * [experimental] Maximum total size of task output cache entries.
     */
    cache_max_size?: string;
    /**
     * @deprecated
     * Compatibility alias for task.cache.remote_mode.
     */
    cache_remote_mode?: "read-write" | "read-only" | "write-only";
    /**
     * @deprecated
     * Compatibility alias for task.cache.remote_namespace.
     */
    cache_remote_namespace?: string;
    /**
     * @deprecated
     * Compatibility alias for task.cache.remote_oidc_audience.
     */
    cache_remote_oidc_audience?: string;
    /**
     * @deprecated
     * Compatibility alias for task.cache.remote_token.
     */
    cache_remote_token?: string;
    /**
     * @deprecated
     * Compatibility alias for task.cache.remote_token_file.
     */
    cache_remote_token_file?: string;
    /**
     * @deprecated
     * Compatibility alias for task.cache.remote_url.
     */
    cache_remote_url?: string;
    /**
     * Paths that mise will not look for tasks in.
     */
    disable_paths?: string[];
    /**
     * Opt out of parsing task run scripts to infer the usage spec (arguments and flags). When enabled, mise will derive the usage spec only from the `usage` field, ignoring any `arg()`, `option()`, or `flag()` templates used in run scripts. This can restore previous behavior and avoid the extra template pass over run scripts when collecting specs.
     */
    disable_spec_from_run_scripts?: boolean;
    /**
     * Maximum depth to search for task files in monorepo subdirectories.
     */
    monorepo_depth?: number;
    /**
     * Directory patterns to exclude when discovering monorepo subdirectories.
     */
    monorepo_exclude_dirs?: string[];
    /**
     * Whether to respect .gitignore files when discovering monorepo subdirectories.
     */
    monorepo_respect_gitignore?: boolean;
    /**
     * Change output style when executing tasks.
     */
    output?: "prefix" | "interleave" | "keep-order" | "replacing" | "timed" | "quiet" | "silent";
    /**
     * Mise will always fetch the latest tasks from the remote, by default the cache is used.
     */
    remote_no_cache?: boolean;
    /**
     * Automatically install missing tools when executing tasks.
     */
    run_auto_install?: boolean;
    /**
     * Disable truncation of command lines in task execution output. When true, the full command line will be shown.
     */
    show_full_cmd?: boolean;
    /**
     * Tasks to skip when running `mise run`.
     */
    skip?: string[];
    /**
     * Run only specified tasks skipping all dependencies.
     */
    skip_depends?: boolean;
    /**
     * When source mtime equals output mtime, consider sources fresh (use <=). Default false uses strict < comparison.
     */
    source_freshness_equal_mtime_is_fresh?: boolean;
    /**
     * Use content hashing (blake3) instead of metadata for source freshness. More accurate but slower.
     */
    source_freshness_hash_contents?: boolean;
    /**
     * Default timeout for tasks.
     */
    timeout?: string;
    /**
     * Show completion message with elapsed time for each task on `mise run`. Default shows when output type is `prefix`.
     */
    timings?: boolean;
    [k: string]: unknown;
  };
  /**
   * @deprecated
   * Paths that mise will not look for tasks in.
   */
  task_disable_paths?: string[];
  /**
   * @deprecated
   * Change output style when executing tasks.
   */
  task_output?: string;
  /**
   * @deprecated
   * Mise will always fetch the latest tasks from the remote, by default the cache is used.
   */
  task_remote_no_cache?: boolean;
  /**
   * @deprecated
   * Automatically install missing tools when executing tasks.
   */
  task_run_auto_install?: boolean;
  /**
   * @deprecated
   * Disable truncation of command lines in task execution output. When true, the full command line will be shown.
   */
  task_show_full_cmd?: boolean;
  /**
   * @deprecated
   * Tasks to skip when running `mise run`.
   */
  task_skip?: string[];
  /**
   * @deprecated
   * Run only specified tasks skipping all dependencies.
   */
  task_skip_depends?: boolean;
  /**
   * @deprecated
   * Default timeout for tasks. Can be overridden by individual tasks.
   */
  task_timeout?: string;
  /**
   * @deprecated
   * Show completion message with elapsed time for each task on `mise run`. Default shows when output type is `prefix`.
   */
  task_timings?: boolean;
  /**
   * @deprecated
   * Use Tera v1 instead of Tera v2 for template rendering.
   */
  tera_v1?: boolean;
  /**
   * Enable terminal progress indicators (OSC 9;4) for compatible terminals.
   */
  terminal_progress?: boolean;
  /**
   * Sets log level to trace
   */
  trace?: boolean;
  /**
   * This is a list of config paths that mise will automatically mark as trusted. Any config files under these paths will be trusted without prompting. Set to `["/"]` to trust all config files, effectively disabling the trust mechanism. Paths are separated by the OS path separator when using the environment variable, `mise settings set`, or `mise settings add` (`:` on Unix, `;` on Windows).
   */
  trusted_config_paths?: string[];
  /**
   * Default shell arguments for Unix to be used for file commands. For example, `sh` for sh.
   */
  unix_default_file_shell_args?: string;
  /**
   * Default shell arguments for Unix to be used for inline commands. For example, `sh -c` for sh.
   */
  unix_default_inline_shell_args?: string;
  upgrade?: {
    /**
     * Uninstall the version `mise upgrade` replaced once the new one has installed.
     */
    auto_prune?: boolean;
    [k: string]: unknown;
  };
  /**
   * Map of URL patterns to replacement URLs applied to all requests.
   */
  url_replacements?: {
    [k: string]: string;
  };
  /**
   * Determines whether to use a specified shell for executing tasks in the tasks directory. When set to true, the shell defined in the file will be used, or the default shell specified by `windows_default_file_shell_args` or `unix_default_file_shell_args` will be applied. If set to false, tasks will be executed directly as programs.
   */
  use_file_shell_for_executable_tasks?: boolean;
  /**
   * Set to false to disable using the mise-versions API for version lists, public GitHub release metadata, and GitHub artifact attestations.
   */
  use_versions_host?: boolean;
  /**
   * Send anonymous download statistics when installing tools.
   */
  use_versions_host_track?: boolean;
  /**
   * Shows more verbose output such as installation logs when installing tools.
   */
  verbose?: boolean;
  /**
   * Default shell arguments for Windows to be used for file commands. For example, `cmd /c` for cmd.exe.
   */
  windows_default_file_shell_args?: string;
  /**
   * Default shell arguments for Windows to be used for inline commands. For example, `cmd /c` for cmd.exe.
   */
  windows_default_inline_shell_args?: string;
  /**
   * List of executable extensions for Windows. For example, `exe` for .exe files, `bat` for .bat files, and so on.
   */
  windows_executable_extensions?: string[];
  /**
   * Pass `-NoProfile` to PowerShell (`pwsh`/`powershell`) shells that mise spawns for tasks and inline commands, so startup profiles are skipped.
   */
  windows_powershell_no_profile?: boolean;
  /**
   * Shim file mode for Windows. Options: `exe`, `file`, `hardlink`, `symlink`.
   */
  windows_shim_mode?: string;
  /**
   * This will automatically answer yes or no to prompts. This is useful for scripting.
   */
  yes?: boolean;
  zig?: {
    /**
     * Download Zig from community-maintained mirrors
     */
    use_community_mirrors?: boolean;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
/**
 * calendar schedule fields for launchd StartCalendarInterval
 */
export interface LaunchdCalendarInterval {
  minute?: number;
  hour?: number;
  day?: number;
  weekday?: number;
  month?: number;
}
export interface SystemdService {
  [k: string]: unknown;
}
/**
 * configuration for task execution and management
 */
export interface TaskConfig {
  /**
   * cascade task configuration to descendant config roots
   */
  cascade?: boolean;
  /**
   * default directory to run tasks in defined in this file
   */
  dir?: string;
  /**
   * default shell to run tasks with in this config scope
   */
  shell?: string;
  /**
   * default experimental local artifact cache configuration for eligible tasks with sources and explicit outputs
   */
  cache?: {
    /**
     * store and restore eligible task outputs from the local mise cache
     */
    enabled?: boolean;
    /**
     * report project files read or written outside declared cache sources and outputs
     */
    audit?: boolean;
    /**
     * ambient environment variable names whose values affect eligible task cache keys
     */
    env?: string[];
    /**
     * commands whose stdout and stderr affect eligible task cache keys
     */
    command_inputs?: string[];
    [k: string]: unknown;
  };
  /**
   * default experimental Rust compiler action cache configuration for tasks in this config scope
   */
  rust_cache?:
    | boolean
    | {
        enabled?: boolean;
        [k: string]: unknown;
      };
  /**
   * experimental ambient environment variable names added to every enabled task cache key in this config scope
   */
  global_env?: string[];
  /**
   * experimental ambient environment variable names preserved under environment denial without affecting task cache keys
   */
  global_pass_through_env?: string[];
  /**
   * experimental config-root-relative source patterns added to every task in this config scope; entries may reference input groups with @group:<name>
   */
  global_inputs?: string[];
  /**
   * experimental reusable config-root-relative source groups referenced with @group:<name>
   */
  input_groups?: {
    [k: string]: string[];
  };
  /**
   * files/directories to include searching for tasks. Can be local paths or git repository URLs using git:: prefix (e.g., git::https://github.com/org/repo.git//path?ref=branch)
   */
  includes?: string[];
  [k: string]: unknown;
}
/**
 * policy for tools declared by this config root
 */
export interface ToolConfig {
  /**
   * require tools declared by this config root to resolve and install from their lockfiles
   */
  locked?: boolean;
  [k: string]: unknown;
}
/**
 * hooks to run on events like cd, enter, leave
 */
export interface Hooks {
  enter?: HookDefinition;
  leave?: HookDefinition;
  cd?: HookDefinition;
  preinstall?: HookInstallDefinition;
  postinstall?: HookInstallDefinition;
}
export interface HookCurrentShellScriptTable {
  /**
   * script or scripts to evaluate in the active shell for enter/leave/cd hooks
   */
  script: string | string[];
  /**
   * active shell name for current-shell hooks, such as "bash"
   */
  shell: string;
  [k: string]: unknown;
}
export interface HookCurrentShellScriptsTable {
  scripts: HookScriptsValue;
  /**
   * active shell name for current-shell hooks, such as "bash"
   */
  shell: string;
  [k: string]: unknown;
}
/**
 * @deprecated
 */
export interface HookSpawnedScriptTable {
  /**
   * @deprecated
   * deprecated alias for run when an enter/leave/cd hook has no shell
   */
  script: string | string[];
  [k: string]: unknown;
}
/**
 * @deprecated
 */
export interface HookSpawnedScriptsTable {
  scripts: HookScriptsValue1;
  [k: string]: unknown;
}
export interface HookTaskRef {
  /**
   * mise task to run
   */
  task: string;
  [k: string]: unknown;
}
/**
 * @deprecated
 */
export interface HookInstallScriptTable {
  /**
   * @deprecated
   * deprecated alias for run in preinstall/postinstall hooks; executes in a subprocess
   */
  script: string | string[];
  /**
   * ignored for this deprecated form; use a run hook to select an inline shell
   */
  shell?: string;
  [k: string]: unknown;
}
/**
 * @deprecated
 */
export interface HookInstallScriptsTable {
  scripts: HookScriptsValue2;
  /**
   * ignored for this deprecated form; use a run hook to select an inline shell
   */
  shell?: string;
  [k: string]: unknown;
}
/**
 * variables to set
 */
export interface Vars1 {
  /**
   * vars modules
   */
  _?: {
    file?: string | string[];
    source?: string | string[];
    [k: string]: unknown;
  };
  [k: string]:
    | string
    | number
    | true
    | {
        value: string | number | true;
        redact?: EnvRedact;
        [k: string]: unknown;
      }
    | {
        default: EnvDefault;
        redact?: EnvRedact;
        [k: string]: unknown;
      }
    | {
        redact?: EnvRedact;
        required: true | string;
        [k: string]: unknown;
      }
    | {
        age: EnvAge;
        redact?: EnvRedact;
        [k: string]: unknown;
      }
    | {
        /**
         * [experimental] age-encrypted value (complex format)
         */
        age: {
          value: EnvAgeValue;
          format?: EnvAgeFormat;
          redact?: EnvRedact;
          [k: string]: unknown;
        };
        [k: string]: unknown;
      };
}
